### PR TITLE
Fix JAR version number in EMR example script

### PR DESCRIPTION
**Pull request by pvdb**
Hey @alexanderdean, just a quick fix to the JAR version number in the EMR example script _(this change was overlooked in 367d82cf, where other version tweaks were applied)_ ... thanks!

### CODE REVIEW

**Comment by alexdean** [comment]
@pvdb: I think you must be looking for somebody else? I haven't worked on this project. Looks interesting, though!

**Comment by alexanderdean** [comment]
Lol sorry @alexdean, it was me :-)

**Comment by alexdean** [comment]
@alexanderdean just figured that out. Greetings, Doppelgänger. :)

**Comment by alexanderdean** [comment]
It's spooky!

**Comment by pvdb** [comment]
@alexdean - soz, you're right: I was trying to tag @alexanderdean :smile:

**Comment by pvdb** [comment]
> It's spooky!

The pull request?!?  :smiley:

**Comment by pvdb** [comment]
Is this PR no good?!?  :wink:

**Comment by alexanderdean** [comment]
No it's fine - thanks, merged!

**Pull request merged**
